config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :restaurants do
      resources :reviews
    end
  end

  resources :restaurants, only: [:index, :show, :new, :create]

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/admin/restaurants_controller.rb
    # Let's anticipate on next week (with login)
class Admin::RestaurantsController < ApplicationController
    before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

    def index
      @restaurants = Restaurant.all
    end

    def show
    end


    def edit
    end

    def update
      if @restaurant.update(restaurant_params)
        redirect_to restaurant_path(@restaurant)
      else
        render :edit
      end
    end

    def destroy
      @restaurant.destroy
      redirect_to restaurants_path
    end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
    before_action :find_review

    def new
      @restaurant = Restaurant.find(params[:restaurant_id])
      @review = Review.new
    end


    def show
    end


    def edit
    end

    def update
      if @review.update(review_params)
        redirect_to admin_review_path(@review)
      else
        render :edit
      end
    end

    def destroy
      @review.destroy
      redirect_to admin_restaurant_path(@restaurant)
    end

  private

  def find_review
    @review = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  # def create
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   @review = Review.new(review_params)
  #   @review.restaurant = @restaurant
  #   if @review.save
  #     redirect_to restaurant_path(@restaurant)
  #   else
  #     render :new
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :find_restaurant, only: [ :show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
    redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/restaurants/index.html.erb
<h1>Restaurants</h1>

Vous êtes connecté en tant qu'administrateur 😎
<br><br>
<ul>
 <% @restaurants.each do |restau| %>
<li><%= restau.name %> | <%= restau.address %> | <%= restau.category %>
<%= link_to "See details", admin_restaurant_path(restau), class: "btn btn-primary"%>

<% end %>
</li>
</ul>

app/views/admin/restaurants/show.html.erb
<h1><%= @restaurant.name%></h1>

Vous êtes connecté en tant qu'administrateur 😎
<br><br>

<ul>
<li> 💎 <%= @restaurant.address %></li>
<li> 🏢  <%= @restaurant.category %></li>
<li> 📞  <%= @restaurant.phone_number %></li>
</ul>

<br><br>
<strong> Reviews : </strong>

<ul>
 <% @restaurant.reviews.each do |review| %>
<li><%= review.content %> | <%= review.rating %> • <%= link_to '❌', admin_restaurant_review_path(@restaurant),
  method: :delete,
  data: { confirm: "Are you sure?" } %>
<% end %>
</li>
</ul>
<br><br>

<%= link_to "Back", admin_restaurants_path, class: "btn btn-primary"%>

app/views/admin/reviews/destroy.html.erb
destroy.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1><%= link_to "👻", admin_restaurants_path %>


<ul>
 <% @restaurants.each do |restau| %>
<li><%= restau.name %> | <%= restau.address %> | <%= restau.category %>
<%= link_to "See details", restaurant_path(restau), class: "btn btn-primary"%>
<% end %>
</li>
</ul>

<%= link_to "➕Add restaurant", new_restaurant_path, class: "btn btn-primary"%>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name%></h1>

<ul>
<li> 💎 <%= @restaurant.address %></li>
<li> 🏢  <%= @restaurant.category %></li>
<li> 📞  <%= @restaurant.phone_number %></li>
</ul>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-success"%>

<br><br>
<strong> Reviews : </strong>

<ul>
 <% @restaurant.reviews.each do |review| %>
<li><%= review.content %> | <%= review.rating %>
<% end %>
</li>
</ul>
<br><br>

<%= link_to "Back", restaurants_path, class: "btn btn-primary"%>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/create.html.erb
<!-- <h1>New review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>
 -->

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>